### ISSUE TITLE
Start versioning this repo

### ISSUE THREAD

**Issue by ryansanford** [flywheel-io/gears#7]
There's a desire to start versioning this repo so applications can reference the contained python module in a reliable and intuitive way without needing to specify a commit hash.

@kofalt @gsfr I'd like your comments on whether an effort should be made to align the python module version with the version of the spec, and fi so, how to accomplish that.

This is related to https://github.com/scitran/core/pull/559

Thanks.

**Comment by ryansanford** [comment]
@kofalt 

Have a preference with a version tag to start off with? I propose using semver, and starting within 0.x.x until we have agreement that the spec and library are considered "stable".

**Comment by kofalt** [comment]
SGTM

**Comment by kofalt** [comment]
I am bumping the version in #14. My decision is that any change to operational concerns - that is, more than just a documentation change - must increment the version. #14 is an example of this, as it broadens the set of manifests we accept.

In anticipation of #14 being the next change to land, I have tagged 17c95bd as `v0.1.0`. My opinion is that each version-bump PR landing is a good time to tag the new version alongside.

We could also do branches, `v0.1`, but I've judged that we don't currently need that. Imports of this module are very scarce, and non-major version bumps should by design be unsurprising.
